// save buyers
export const ACTIVATE_ACCOUNT_START = 'ACTIVATE_ACCOUNT_START';
export const ACTIVATE_ACCOUNT_END = 'ACTIVATE_ACCOUNT_END';
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS';
export const ACTIVATE_ACCOUNT_FAILURE = 'ACTIVATE_ACCOUNT_FAILURE';
