//
export const CREATE_AGENCIES_START = 'CREATE_AGENCIES_START';
export const CREATE_AGENCIES_END = 'CREATE_AGENCIES_END';
export const CREATE_AGENCIES_SUCCESS = 'CREATE_AGENCIES_SUCCESS';
export const CREATE_AGENCIES_FAILURE = 'CREATE_AGENCIES_FAILURE';
