// save buyers
export const SAVE_BUYER_START = 'SAVE_BUYER_START';
export const SAVE_BUYER_END = 'SAVE_BUYER_END';
export const SAVE_BUYER_SUCCESS = 'SAVE_BUYER_SUCCESS';
export const SAVE_BUYER_FAILURE = 'SAVE_BUYER_FAILURE';

// buyer signup
export const BUYER_SIGNUP_START = 'BUYER_SIGNUP_START';
export const BUYER_SIGNUP_END = 'BUYER_SIGNUP_END';
export const BUYER_SIGNUP_SUCCESS = 'BUYER_SIGNUP_SUCCESS';
export const BUYER_SIGNUP_FAILURE = 'BUYER_SIGNUP_FAILURE';

// buyer signup
export const BUY_ITEM_START = 'BUY_ITEM_START';
export const BUY_ITEM_END = 'BUY_ITEM_END';
export const BUY_ITEM_SUCCESS = 'BUY_ITEM_SUCCESS';
export const BUY_ITEM_FAILURE = 'BUY_ITEM_FAILURE';
