export const GET_SHOPPING_CART_ITEMS_START = 'GET_SHOPPING_CART_ITEMS_START';
export const GET_SHOPPING_CART_ITEMS_END = 'GET_SHOPPING_CART_ITEMS_END';
export const GET_SHOPPING_CART_ITEMS_SUCCESS = 'GET_SHOPPING_CART_ITEMS_SUCCESS';
export const GET_SHOPPING_CART_ITEMS_FAILURE = 'GET_SHOPPING_CART_ITEMS_FAILURE';
