export const GET_ALL_ORDERS_START = 'GET_ALL_ORDERS_START';
export const GET_ALL_ORDERS_END = 'GET_ALL_ORDERS_END';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_END = 'DELETE_ORDER_END';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';
