// signin actions types
export const CREATE_NEW_PRODUCT_START = 'CREATE_NEW_PRODUCT_START';
export const CREATE_NEW_PRODUCT_END = 'CREATE_NEW_PRODUCT_END';
export const CREATE_NEW_PRODUCT_SUCCESS = 'CREATE_NEW_PRODUCT_SUCCESS';
export const CREATE_NEW_PRODUCT_FAILURE = 'CREATE_NEW_PRODUCT_FAILURE';
