// Seller actions types
export const SAVE_SELLER_START = 'SAVE_SELLER_START';
export const SAVE_SELLER_END = 'SAVE_SELLER_END';
export const SAVE_SELLER_SUCCESS = 'SAVE_SELLER_SUCCESS';
export const SAVE_SELLER_FAILURE = 'SAVE_SELLER_FAILURE';

// edit seller information

export const EDIT_SELLER_START = 'EDIT_SELLER_START';
export const EDIT_SELLER_END = 'EDIT_SELLER_END';
export const EDIT_SELLER_SUCCESS = 'EDIT_SELLER_SUCCESS';
export const EDIT_SELLER_FAILURE = 'EDIT_SELLER_FAILURE';
